/**
 * Generates docs/TUNING.md from the data modules, so the tuning reference can never drift from the code.
 *   node tools/tuning-doc.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { PROOF_SPEED_FACTOR } from '../src/core/gen/passability.ts';
import { certifiedSpeed, cruiseFor, PROFILE } from '../src/core/gen/validation-profile.ts';
import { BIOMES } from '../src/data/biomes.ts';
import { COSMETICS } from '../src/data/cosmetics.ts';
import { DIFFICULTY } from '../src/data/difficulty.ts';
import { ECONOMY } from '../src/data/economy.ts';
import { HAPTICS } from '../src/data/haptics.ts';
import { MISSIONS } from '../src/data/missions.ts';
import { OBSTACLES } from '../src/data/obstacles.ts';
import { PALETTES } from '../src/data/palette.ts';
import { PATTERNS } from '../src/data/patterns.ts';
import { SHIPS } from '../src/data/ships.ts';
import { DT, HALF_H, HALF_W, SHIP_X_LIMIT, SHIP_Y_LIMIT } from '../src/data/tuning.ts';
import { UPGRADES } from '../src/data/upgrades.ts';

const hex = (c: number): string => `\`#${c.toString(16).padStart(6, '0')}\``;
const out: string[] = [];
const p = (s = ''): void => {
  out.push(s);
};
const table = (head: string[], rows: (string | number)[][]): void => {
  p(`| ${head.join(' | ')} |`);
  p(`|${head.map(() => '---').join('|')}|`);
  for (const r of rows) p(`| ${r.join(' | ')} |`);
  p();
};

p('# Tuning reference');
p();
p(
  '> Generated by `npm run docs:tuning` from `src/data/*`. Do not edit by hand: change the data and regenerate.',
);
p();

// Global constants with their doc comments, parsed from the source so the explanations stay attached.
const src = readFileSync('src/data/tuning.ts', 'utf8').split('\n');
let section = '';
let doc = '';
const rows: string[][] = [];
const flush = (): void => {
  if (rows.length === 0) return;
  p(`## ${section}`);
  p();
  table(['Constant', 'Value', 'Meaning'], rows.splice(0));
};
for (const line of src) {
  const sec = line.match(/^\s*\/\/ ## (.+)$/);
  if (sec) {
    flush();
    section = sec[1]!;
    continue;
  }
  const d = line.match(/^\s*\/\*\* (.+?) \*\/\s*$/);
  if (d) {
    doc = d[1]!;
    continue;
  }
  const kv = line.match(/^\s*([A-Z0-9_]+): (.+),\s*$/);
  if (kv && section) {
    rows.push([`\`${kv[1]}\``, `\`${kv[2]}\``, doc]);
    doc = '';
  }
}
flush();

p('## Derived values');
p();
table(
  ['Name', 'Value', 'Meaning'],
  [
    ['`DT`', DT.toFixed(6), 'Seconds per sim tick (1 / SIM_HZ).'],
    ['`HALF_W` / `HALF_H`', `${HALF_W} / ${HALF_H}`, 'Half extents of the lattice (metres).'],
    [
      '`SHIP_X_LIMIT` / `SHIP_Y_LIMIT`',
      `${SHIP_X_LIMIT} / ${SHIP_Y_LIMIT}`,
      'Ship centre clamp (outermost cell centres).',
    ],
    [
      'Proof lateral speed',
      `${PROFILE.vLatMin} m/s × ${PROOF_SPEED_FACTOR}`,
      'Slowest ship, with a safety factor for rounding.',
    ],
    [
      'Proof hitbox',
      `r ${PROFILE.rMax} m, h ${PROFILE.hMax} m`,
      'Largest radius and half-length of any ship.',
    ],
    [
      'Certified speed at d=0 / d=1',
      `${certifiedSpeed(cruiseFor(0), cruiseFor(0)).toFixed(1)} / ${certifiedSpeed(cruiseFor(1), cruiseFor(1)).toFixed(1)} m/s`,
      'Cruise × fastest ship factor × boost.',
    ],
  ],
);

p('## Ships');
p();
table(
  ['Ship', 'Lateral m/s', 'Speed ×', 'Hit radius', 'Half-length', 'Ability', 'Price ◆'],
  SHIPS.map((s) => [
    s.name,
    s.lateralSpeed,
    s.speedFactor,
    s.hitRadius,
    s.hitHalfLength,
    s.abilityName,
    s.price,
  ]),
);

p('## Obstacles');
p();
table(
  ['Id', 'Shape', 'Size (scale 1)', 'Kind', 'Removable by repair', 'Pulse-immune', 'Well (G, a, range)'],
  OBSTACLES.map((o) => [
    `\`${o.id}\``,
    o.shape,
    o.shape === 'sphere' ? `r ${o.radius}` : `½ ${o.half.join(' × ')}`,
    o.kind,
    o.removable ? 'yes' : 'no',
    o.pulseImmune ? 'yes' : 'no',
    o.well ? `${o.well.strength}, ${o.well.softening}, ${o.well.range}` : '–',
  ]),
);

p('## Difficulty curve');
p();
table(
  ['Distance (m)', ...DIFFICULTY.distance.map(String)],
  [['Base difficulty', ...DIFFICULTY.base.map(String)]],
);
table(
  ['Parameter', 'Value'],
  [
    ['minD / maxD', `${DIFFICULTY.minD} / ${DIFFICULTY.maxD}`],
    ['Max change per chunk', DIFFICULTY.maxStep],
    ['Pattern gap (easy → hard, m)', DIFFICULTY.patternGap.join(' → ')],
    ['Density multiplier', DIFFICULTY.density.join(' → ')],
    ['Chunk lead-in (s at certified speed)', DIFFICULTY.leadInSeconds],
    ['Persistent skill offset', `±${DIFFICULTY.skillOffset}`],
    ['In-run offset (max, gain)', `±${DIFFICULTY.inRunOffsetMax}, ${DIFFICULTY.inRunGain}`],
    ['Target near-misses per 100 m', DIFFICULTY.targetNearMissPer100m],
    ['Expected run distance (m)', DIFFICULTY.expectedDistance],
    ['Skill EMA', DIFFICULTY.skillEma],
  ],
);

p('## Biomes');
p();
table(
  ['Biome', 'Fog', 'Nebula A / B / C', 'Rail', 'Grading (sat, contrast)', 'Music cutoff, root'],
  BIOMES.map((b) => [
    b.name,
    hex(b.palette.fog),
    `${hex(b.palette.nebulaA)} ${hex(b.palette.nebulaB)} ${hex(b.palette.nebulaC)}`,
    hex(b.palette.rail),
    `${b.grading.saturation}, ${b.grading.contrast}`,
    `${b.music.cutoff} Hz, MIDI ${b.music.root}`,
  ]),
);

p('## Patterns');
p();
table(
  ['Pattern', 'Biomes', 'Difficulty', 'Weight', 'Length (m)', 'Elements'],
  PATTERNS.map((x) => [
    `\`${x.id}\``,
    x.biomes.join(', '),
    `${x.minD}–${x.maxD}`,
    x.weight,
    x.length,
    x.elements.map((e) => `${e.type}(${e.obstacle})`).join(', ') || 'empty (breather)',
  ]),
);

p('## Upgrades');
p();
table(
  ['Upgrade', 'Branch', 'Effect per level', 'Costs ◆', 'Requires'],
  UPGRADES.map((u) => [
    u.name,
    u.branch,
    `${u.stat} +${u.perLevel}`,
    u.costs.join(' / '),
    u.requires.join(', ') || '–',
  ]),
);

p('## Economy');
p();
table(
  ['Constant', 'Value'],
  Object.entries(ECONOMY).map(([k, v]) => [`\`${k}\``, String(v)]),
);

p('## Daily missions');
p();
table(
  ['Mission', 'Target range', 'Step', 'Reward ◆'],
  MISSIONS.map((m) => [m.text, m.target.join('–'), m.step, m.reward]),
);

p('## Cosmetics');
p();
table(
  ['Item', 'Kind', 'Colour', 'Price ◆'],
  COSMETICS.map((c) => [c.name, c.kind, c.colors.length ? hex(c.colors[0]!) : 'stock', c.price]),
);

p('## Haptics');
p();
table(
  ['Event', 'Pattern (ms on/off)', 'Cooldown (ms)'],
  Object.entries(HAPTICS).map(([k, v]) => [k, v.pattern.join(', '), v.cooldown]),
);

p('## Colour palettes');
p();
table(
  ['Role', 'Standard (Okabe–Ito)', 'High contrast'],
  (Object.keys(PALETTES.standard) as (keyof typeof PALETTES.standard)[]).map((k) => [
    k,
    hex(PALETTES.standard[k]),
    hex(PALETTES.highContrast[k]),
  ]),
);

try {
  const audio = await import('../src/data/audio.ts');
  const cues = (
    audio as {
      AUDIO_CUES?: readonly {
        id: string;
        recipe: string;
        gain: number;
        voices: number;
        cooldownMs: number;
      }[];
    }
  ).AUDIO_CUES;
  if (cues) {
    p('## Audio cues');
    p();
    table(
      ['Cue', 'Recipe', 'Gain', 'Voices', 'Cooldown (ms)'],
      cues.map((c) => [c.id, c.recipe, c.gain, c.voices, c.cooldownMs]),
    );
  }
  const music = (audio as unknown as { MUSIC?: Record<string, unknown> }).MUSIC;
  if (music) {
    p('## Adaptive music');
    p();
    const flat: (string | number)[][] = [];
    const walk = (prefix: string, v: unknown): void => {
      if (typeof v === 'number' || typeof v === 'string' || typeof v === 'boolean')
        flat.push([`\`${prefix}\``, String(v)]);
      else if (Array.isArray(v)) {
        if (v.every((x) => typeof x === 'number')) flat.push([`\`${prefix}\``, v.join(', ')]);
      } else if (v && typeof v === 'object') {
        for (const [k, x] of Object.entries(v)) walk(prefix ? `${prefix}.${k}` : k, x);
      }
    };
    walk('', music);
    const layers = (music.layers ?? []) as { id: string; gain: number }[];
    for (const l of layers) flat.push([`\`layer ${l.id}\``, `gain ${l.gain}`]);
    table(['Parameter', 'Value'], flat);
  }
} catch {
  /* audio data not present */
}

writeFileSync('docs/TUNING.md', `${out.join('\n')}\n`);
console.log(`docs/TUNING.md written (${out.length} lines)`);
